// =============================================================================
// RoadMapReader camera fixture validation
//
// Loads the ALPR-only camera fixture (test/fixtures/camera_types_road_map.bin),
// generated by test/fixtures/tools/generate_camera_fixture.py, through the real
// RoadMapReader path and verifies that nearestCamera() resolves the stored ALPR
// record correctly.
// =============================================================================

#include <unity.h>
#include <cstdio>
#include <vector>

#include "../mocks/Arduino.h"

#ifndef ARDUINO
SerialClass Serial;
unsigned long mockMillis = 0;
unsigned long mockMicros = 0;
#endif

#include "../../src/modules/lockout/road_map_reader.h"
#include "../../src/modules/lockout/road_map_reader.cpp"

static uint8_t* fixtureData = nullptr;
static uint32_t fixtureSize = 0;

static bool loadFixtureFile(const char* path) {
	FILE* f = fopen(path, "rb");
	if (!f) return false;
	fseek(f, 0, SEEK_END);
	fixtureSize = static_cast<uint32_t>(ftell(f));
	fseek(f, 0, SEEK_SET);
	fixtureData = new uint8_t[fixtureSize];
	size_t n = fread(fixtureData, 1, fixtureSize, f);
	fclose(f);
	return n == fixtureSize;
}

static constexpr int32_t CAM_LAT = 3974600;
static constexpr int32_t CAM_LON = -10499050;

void test_loadFromBuffer_succeeds() {
	RoadMapReader reader;
	TEST_ASSERT_TRUE_MESSAGE(
		reader.loadFromBuffer(fixtureData, fixtureSize),
		"loadFromBuffer should return true for valid fixture");
	TEST_ASSERT_TRUE(reader.isLoaded());
}

void test_camera_count_is_1() {
	RoadMapReader reader;
	reader.loadFromBuffer(fixtureData, fixtureSize);
	TEST_ASSERT_EQUAL_UINT32(1, reader.cameraCount());
}

void test_segment_count_is_1() {
	RoadMapReader reader;
	reader.loadFromBuffer(fixtureData, fixtureSize);
	TEST_ASSERT_EQUAL_UINT32(1, reader.segmentCount());
}

void test_nearest_camera_type_alpr() {
	RoadMapReader reader;
	reader.loadFromBuffer(fixtureData, fixtureSize);
	CameraResult r = reader.nearestCamera(CAM_LAT, CAM_LON, 900);
	TEST_ASSERT_TRUE_MESSAGE(r.valid, "ALPR camera not found");
	TEST_ASSERT_EQUAL_UINT8(4, r.flags);
	TEST_ASSERT_EQUAL_UINT8(30, r.speedMph);
	TEST_ASSERT_EQUAL_UINT16(0xFFFF, r.bearing);
}

void test_no_camera_outside_grid() {
	RoadMapReader reader;
	reader.loadFromBuffer(fixtureData, fixtureSize);
	CameraResult r = reader.nearestCamera(0, 0, 900);
	TEST_ASSERT_FALSE(r.valid);
}

void test_camera_distance_exceeds_legacy_uint16_cap() {
	RoadMapReader reader;
	reader.loadFromBuffer(fixtureData, fixtureSize);

	CameraResult r = reader.nearestCamera(CAM_LAT - 600, CAM_LON, 900);
	TEST_ASSERT_TRUE_MESSAGE(r.valid, "far camera query should still resolve");
	TEST_ASSERT_EQUAL_UINT8(4, r.flags);
	TEST_ASSERT_TRUE_MESSAGE(r.distanceCm > 65534u,
							 "camera distance should exceed legacy uint16_t cap");
}

void test_loadFromBuffer_rejects_bad_magic() {
	std::vector<uint8_t> bad(fixtureData, fixtureData + fixtureSize);
	bad[0] = 'X';
	RoadMapReader reader;
	TEST_ASSERT_FALSE(reader.loadFromBuffer(bad.data(), fixtureSize));
	TEST_ASSERT_FALSE(reader.isLoaded());
}

void test_loadFromBuffer_rejects_short_buffer() {
	RoadMapReader reader;
	TEST_ASSERT_FALSE(reader.loadFromBuffer(fixtureData, 32));
}

void test_failed_reload_clears_prior_state() {
	RoadMapReader reader;
	TEST_ASSERT_TRUE(reader.loadFromBuffer(fixtureData, fixtureSize));

	std::vector<uint8_t> bad(fixtureData, fixtureData + fixtureSize);
	bad[0] = 'X';

	TEST_ASSERT_FALSE(reader.loadFromBuffer(bad.data(), fixtureSize));
	TEST_ASSERT_FALSE(reader.isLoaded());
	TEST_ASSERT_EQUAL_UINT32(0, reader.cameraCount());

	CameraResult r = reader.nearestCamera(CAM_LAT, CAM_LON, 900);
	TEST_ASSERT_FALSE(r.valid);
}

void test_reload_without_camera_section_clears_camera_lookup() {
	RoadMapReader reader;
	TEST_ASSERT_TRUE(reader.loadFromBuffer(fixtureData, fixtureSize));

	std::vector<uint8_t> noCams(fixtureData, fixtureData + fixtureSize);
	memset(noCams.data() + 56, 0, 8);

	TEST_ASSERT_TRUE(reader.loadFromBuffer(noCams.data(), fixtureSize));
	TEST_ASSERT_TRUE(reader.isLoaded());
	TEST_ASSERT_EQUAL_UINT32(0, reader.cameraCount());

	CameraResult r = reader.nearestCamera(CAM_LAT, CAM_LON, 900);
	TEST_ASSERT_FALSE(r.valid);
}

int main() {
	if (!loadFixtureFile("test/fixtures/camera_types_road_map.bin")) {
		if (!loadFixtureFile("../../test/fixtures/camera_types_road_map.bin")) {
			fprintf(stderr, "FATAL: cannot open camera fixture\n");
			return 1;
		}
	}

	UNITY_BEGIN();
	RUN_TEST(test_loadFromBuffer_succeeds);
	RUN_TEST(test_camera_count_is_1);
	RUN_TEST(test_segment_count_is_1);
	RUN_TEST(test_nearest_camera_type_alpr);
	RUN_TEST(test_no_camera_outside_grid);
	RUN_TEST(test_camera_distance_exceeds_legacy_uint16_cap);
	RUN_TEST(test_loadFromBuffer_rejects_bad_magic);
	RUN_TEST(test_loadFromBuffer_rejects_short_buffer);
	RUN_TEST(test_failed_reload_clears_prior_state);
	RUN_TEST(test_reload_without_camera_section_clears_camera_lookup);
	int result = UNITY_END();

	delete[] fixtureData;
	return result;
}
