// Camera Alert Manager
// Loads and queries red light camera / speed camera / ALPR databases
// Data format: NDJSON (newline-delimited JSON) compatible with RDForum ExCam format

#ifndef CAMERA_MANAGER_H
#define CAMERA_MANAGER_H

#include <Arduino.h>
#include <vector>
#include <atomic>
#include <FS.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <freertos/semphr.h>
#include <esp_heap_caps.h>

// PSRAM allocator for std::vector - keeps camera data off precious SRAM heap
// ESP32-S3 has 8MB PSRAM vs ~320KB SRAM, so camera DB belongs in PSRAM
template <typename T>
struct PSRAMAllocator {
  using value_type = T;
  using size_type = std::size_t;
  using difference_type = std::ptrdiff_t;
  
  PSRAMAllocator() = default;
  template <typename U> PSRAMAllocator(const PSRAMAllocator<U>&) noexcept {}
  
  T* allocate(std::size_t n) {
    if (n > std::size_t(-1) / sizeof(T)) {
      return nullptr;  // Overflow check
    }
    // Try PSRAM first, fall back to regular heap if PSRAM unavailable
    void* ptr = heap_caps_malloc(n * sizeof(T), MALLOC_CAP_SPIRAM | MALLOC_CAP_8BIT);
    if (!ptr) {
      ptr = heap_caps_malloc(n * sizeof(T), MALLOC_CAP_DEFAULT);
    }
    return static_cast<T*>(ptr);
  }
  
  void deallocate(T* ptr, std::size_t) noexcept {
    heap_caps_free(ptr);
  }
  
  template <typename U> bool operator==(const PSRAMAllocator<U>&) const noexcept { return true; }
  template <typename U> bool operator!=(const PSRAMAllocator<U>&) const noexcept { return false; }
};

// Camera types (matches ExCam flg values)
enum class CameraType : uint8_t {
  RedLightAndSpeed = 1,  // flg=1: Red light camera with speed enforcement
  SpeedCamera = 2,       // flg=2: Speed camera only
  RedLightCamera = 3,    // flg=3: Red light camera only
  ALPR = 4,              // Custom: Automatic License Plate Reader
  Unknown = 0
};

// Compact camera record (~32 bytes per camera with corridor data)
struct CameraRecord {
  float latitude;
  float longitude;
  uint8_t type;           // CameraType
  uint8_t speedLimit;     // 0 if unknown, in display units
  uint8_t directionCount; // 0-2 directions
  uint16_t directions[2]; // Up to 2 directions (0-359 degrees)
  bool isMetric;          // true = kmh, false = mph
  
  // Road corridor metadata for filtering side-road false alerts
  int16_t roadBearing;       // Road direction at camera (0-359, -1 = unknown)
  uint8_t corridorWidthM;    // Half-width of road corridor in meters (25-50 typical)
  uint8_t bearingTolerance;  // ±degrees for heading match (25-35 typical)
  float snapLat;             // Road snap point latitude (for cross-track calc)
  float snapLon;             // Road snap point longitude
  
  // Check if corridor data is available
  bool hasCorridorData() const { return roadBearing >= 0; }
  
  CameraType getCameraType() const { return static_cast<CameraType>(type); }
  
  // Get type name for display (full readable name for main display)
  const char* getTypeName() const {
    switch (getCameraType()) {
      case CameraType::RedLightAndSpeed: return "RED LIGHT + SPEED";
      case CameraType::SpeedCamera: return "SPEED";
      case CameraType::RedLightCamera: return "RED LIGHT";
      case CameraType::ALPR: return "ALPR";
      default: return "CAMERA";
    }
  }
  
  // Get short type name for card display (fits in secondary card bottom row)
  const char* getShortTypeName() const {
    switch (getCameraType()) {
      case CameraType::RedLightAndSpeed: return "RLC+SPD";
      case CameraType::SpeedCamera: return "SPEED";
      case CameraType::RedLightCamera: return "RED LIGHT";
      case CameraType::ALPR: return "ALPR";
      default: return "CAMERA";
    }
  }
};

// Result for nearby camera queries
struct NearbyCameraResult {
  CameraRecord camera;
  float distance_m;     // Distance in meters
  float bearing_deg;    // Bearing to camera (0-359)
  bool isApproaching;   // True if heading towards camera
};

// Grid cell for spatial indexing
struct GridCell {
  uint16_t startIndex;
  uint16_t count;
};

// Type aliases for PSRAM-backed vectors (keep camera data off SRAM heap)
using CameraVector = std::vector<CameraRecord, PSRAMAllocator<CameraRecord>>;
using GridVector = std::vector<GridCell, PSRAMAllocator<GridCell>>;

class CameraManager {
public:
  CameraManager();
  ~CameraManager();
  
  // Initialize and load database from SD card
  // Returns true if database loaded successfully
  bool begin(fs::FS* filesystem);
  
  // Load camera database from file (NDJSON format)
  // Supports: V1 ExCam JSON format, POI Factory CSV (future)
  // append: if true, add to existing cameras; if false, clear first
  bool loadDatabase(const char* path, bool append = false);
  
  // Load camera database from binary format (10-20x faster than JSON)
  // Binary files are generated by convert_to_binary.py tool
  // append: if true, add to existing cameras; if false, clear first
  bool loadBinaryDatabase(const char* path, bool append = false);
  
  // Clear all loaded cameras
  void clear();
  
  // Get database info
  size_t getCameraCount() const { return cameras.size(); }
  size_t getRegionalCacheCount() const { return regionalCache.size(); }
  const char* getDatabaseName() const { return databaseName; }
  const char* getDatabaseDate() const { return databaseDate; }
  bool isLoaded() const { return !cameras.empty() || !regionalCache.empty(); }
  bool hasRegionalCache() const { return !regionalCache.empty(); }
  
  // Regional caching - keeps only cameras within radius of GPS position
  // Call when GPS gets first fix or periodically when user moves significantly
  bool buildRegionalCache(float lat, float lon, float radiusMiles = 100.0f);
  bool needsCacheRefresh(float lat, float lon, float distanceThresholdMiles = 50.0f) const;
  bool saveRegionalCache(fs::FS* filesystem, const char* path = "/cameras_cache.json");
  bool loadRegionalCache(fs::FS* filesystem, const char* path = "/cameras_cache.json");
  void getCacheCenter(float& lat, float& lon) const { lat = cacheCenterLat; lon = cacheCenterLon; }
  float getCacheRadius() const { return cacheRadiusMi; }
  
  // Incremental (non-blocking) cache building - prevents main loop stalls
  // Call startIncrementalCacheBuild() once, then continueIncrementalCacheBuild() each loop iteration
  bool startIncrementalCacheBuild(float lat, float lon, float radiusMiles = 100.0f);
  bool continueIncrementalCacheBuild(size_t maxCamerasPerIteration = 500);
  bool isIncrementalBuildInProgress() const { return incrementalBuild.inProgress; }
  bool finishIncrementalCacheBuild();  // Swap in completed cache
  
  // Find cameras within radius of current position
  // Populates output vector (cleared first), sorted by distance (closest first)
  // Uses output parameter to avoid allocation - caller provides reusable vector
  // budgetUs: time budget in microseconds (0 = no limit). Returns early if exceeded.
  void findNearby(
    float lat, float lon, 
    float heading_deg,
    float radius_m,
    size_t maxResults,
    std::vector<NearbyCameraResult>& out,
    uint32_t budgetUs = 0
  ) const;
  
  // Quick check if any camera is within alert range
  // More efficient than findNearby for frequent polling
  bool hasNearbyCamera(float lat, float lon, float radius_m = 500.0f) const;
  
  // Get the closest camera (null if none in range)
  bool getClosestCamera(
    float lat, float lon,
    float heading_deg,
    float radius_m,
    NearbyCameraResult& result
  ) const;
  
  // Filter settings
  void setEnabledTypes(bool redLight, bool speed, bool alpr);
  bool isTypeEnabled(CameraType type) const;
  
  // Statistics
  size_t getRedLightCount() const;
  size_t getSpeedCameraCount() const;
  size_t getALPRCount() const;

  // Utility functions (public for external use)
  static float haversineDistance(float lat1, float lon1, float lat2, float lon2);
  static float calculateBearing(float lat1, float lon1, float lat2, float lon2);
  
  // Background loading - non-blocking database load
  // Call setFilesystem() first, then startBackgroundLoad()
  // Load regional cache first for instant alerts, then background load full DB
  void setFilesystem(fs::FS* filesystem) { fs = filesystem; }
  fs::FS* getFilesystem() const { return fs; }
  bool startBackgroundLoad();
  void stopBackgroundLoad();
  bool isBackgroundLoading() const { return backgroundLoading.load(std::memory_order_acquire); }
  int getLoadProgress() const { return loadProgressPercent; }  // 0-100
  size_t getLoadedCount() const;  // Thread-safe camera count

private:
  fs::FS* fs = nullptr;
  CameraVector cameras;          // Full database from SD (in PSRAM)
  CameraVector regionalCache;    // Subset near GPS position (in PSRAM)
  
  // Thread safety for camera vector (modified by background task, read by queries)
  mutable SemaphoreHandle_t cameraMutex = nullptr;
  
  // Background loading state
  TaskHandle_t loadTaskHandle = nullptr;
  std::atomic<bool> backgroundLoading{false};
  volatile bool loadTaskShouldExit = false;
  volatile int loadProgressPercent = 0;
  static void loadTaskEntry(void* param);
  bool loadDatabaseIncremental();  // Called by background task
  size_t loadBinaryDatabaseIncremental(const char* path);  // Fast binary load
  size_t loadJsonDatabaseIncremental(const char* path);    // Slow JSON fallback

  // Returns the active camera list with a safe snapshot when background loading
  const CameraVector* getQueryCamerasSnapshot(
    CameraVector& snapshot
  ) const;
  
  // Regional cache metadata
  float cacheCenterLat = 0.0f;
  float cacheCenterLon = 0.0f;
  float cacheRadiusMi = 0.0f;
  uint32_t cacheBuiltMs = 0;
  
  // Incremental cache build state (for non-blocking cache refresh)
  struct IncrementalCacheBuildState {
    bool inProgress = false;
    size_t currentIndex = 0;
    float targetLat = 0.0f;
    float targetLon = 0.0f;
    float radiusM = 0.0f;
    float radiusMi = 0.0f;  // Store original radius in miles
    float latDelta = 0.0f;
    float lonDelta = 0.0f;
    CameraVector pendingCache;  // In PSRAM
    uint32_t startTimeMs = 0;
    
    void reset() {
      inProgress = false;
      currentIndex = 0;
      pendingCache.clear();
      pendingCache.shrink_to_fit();
    }
  };
  IncrementalCacheBuildState incrementalBuild;
  
  // Database metadata
  char databaseName[64] = {0};
  char databaseDate[16] = {0};
  
  // Type filters
  bool enableRedLight = true;
  bool enableSpeed = true;
  bool enableALPR = true;
  
  // Spatial index (grid-based for memory efficiency, stored in PSRAM)
  static constexpr float GRID_SIZE_DEG = 0.1f;  // ~11km cells
  static constexpr int GRID_LAT_CELLS = 180 * 10;  // 1800 cells
  static constexpr int GRID_LON_CELLS = 360 * 10;  // 3600 cells
  GridVector spatialIndex;
  bool indexBuilt = false;
  
  // Build spatial index for fast queries
  void buildSpatialIndex();
  
  // Get grid cell index for a coordinate
  int getGridIndex(float lat, float lon) const;
  
  // Parse a single NDJSON line
  bool parseCameraLine(const char* line, CameraRecord& record);
  
  // Get cameras to query (regional cache if available, else full database)
  const CameraVector& getQueryCameras() const;
  
  // Check if heading is towards camera (within tolerance)
  static bool isHeadingTowards(float heading, float bearing, float tolerance = 45.0f);
  
  // Corridor matching helpers
  static float angleDiff(float a, float b);
  static float crossTrackDistance(float lat, float lon, 
                                   float roadLat, float roadLon, 
                                   int16_t roadBearing);
  bool isOnCameraRoad(float lat, float lon, float heading,
                      const CameraRecord& cam) const;
};

// Global instance
extern CameraManager cameraManager;

#endif // CAMERA_MANAGER_H
