// Camera Alert Manager Implementation
// Loads NDJSON camera database and provides fast proximity queries

#include "camera_manager.h"
#include "debug_logger.h"
#include <ArduinoJson.h>
#include <algorithm>
#include <cmath>

static constexpr bool DEBUG_LOGS = false;

// Camera logging macro - logs to SD when category enabled
#define CAMERA_LOGF(...) do { \
    if (DEBUG_LOGS) Serial.printf(__VA_ARGS__); \
    if (debugLogger.isEnabledFor(DebugLogCategory::Camera)) debugLogger.logf(DebugLogCategory::Camera, __VA_ARGS__); \
} while(0)

// Global instance
CameraManager cameraManager;

CameraManager::CameraManager() {
  // Reserve space for typical database size
  cameras.reserve(1000);
  
  // Create mutex for thread-safe access to camera vector
  cameraMutex = xSemaphoreCreateMutex();
  if (!cameraMutex) {
    Serial.println("[Camera] WARNING: Failed to create camera mutex!");
  }
}

CameraManager::~CameraManager() {
  // Stop any background loading
  stopBackgroundLoad();
  
  // Delete mutex
  if (cameraMutex) {
    vSemaphoreDelete(cameraMutex);
    cameraMutex = nullptr;
  }
  
  clear();
}

bool CameraManager::begin(fs::FS* filesystem) {
  fs = filesystem;
  if (!fs) {
    Serial.println("[Camera] No filesystem provided");
    return false;
  }
  
  // Clear any existing data first
  clear();
  
  // Try to load default database from SD card
  // Load all available camera database files
  // Prefer binary files (.bin) over JSON for faster loading
  bool loaded = false;
  
  // Primary camera database files (ALPR, red light, speed)
  // Binary format loads 10-20x faster than JSON
  // Generated by tools/download_cameras.py
  if (fs->exists("/alpr.bin")) {
    loaded = loadBinaryDatabase("/alpr.bin", loaded) || loaded;
  } else if (fs->exists("/alpr.json")) {
    loaded = loadDatabase("/alpr.json", loaded) || loaded;
  }
  
  if (fs->exists("/redlight.bin")) {
    loaded = loadBinaryDatabase("/redlight.bin", true) || loaded;
  } else if (fs->exists("/redlight_cam.bin")) {
    // Legacy filename
    loaded = loadBinaryDatabase("/redlight_cam.bin", true) || loaded;
  } else if (fs->exists("/redlight_cam.json")) {
    loaded = loadDatabase("/redlight_cam.json", true) || loaded;
  }
  
  if (fs->exists("/speed.bin")) {
    loaded = loadBinaryDatabase("/speed.bin", true) || loaded;
  } else if (fs->exists("/speed_cam.bin")) {
    // Legacy filename
    loaded = loadBinaryDatabase("/speed_cam.bin", true) || loaded;
  } else if (fs->exists("/speed_cam.json")) {
    loaded = loadDatabase("/speed_cam.json", true) || loaded;
  }
  
  // Legacy/alternative file names (only if no primary files found)
  if (!loaded) {
    if (fs->exists("/cameras.json")) {
      return loadDatabase("/cameras.json", false);
    } else if (fs->exists("/alpr_osm.json")) {
      // Legacy JSON format from older web UI
      return loadDatabase("/alpr_osm.json", false);
    } else if (fs->exists("/V140ExCam.json")) {
      return loadDatabase("/V140ExCam.json", false);
    } else if (fs->exists("/excam.json")) {
      return loadDatabase("/excam.json", false);
    }
  }
  
  if (!loaded && DEBUG_LOGS) {
    Serial.println("[Camera] No camera database found on SD card");
  }
  
  if (loaded) {
    Serial.printf("[Camera] Total cameras loaded: %d\n", cameras.size());
  }
  
  return loaded;
}

bool CameraManager::loadDatabase(const char* path, bool append) {
  if (!fs) return false;
  
  File file = fs->open(path, "r");
  if (!file) {
    Serial.printf("[Camera] Failed to open %s\n", path);
    return false;
  }
  
  // Clear existing data only if not appending
  if (!append) {
    clear();
  }
  
  Serial.printf("[Camera] Loading database from %s...\n", path);
  uint32_t startTime = millis();
  size_t startCount = cameras.size();
  
  size_t lineCount = 0;
  size_t parseErrors = 0;
  char lineBuffer[256];
  size_t bufIdx = 0;
  
  while (file.available()) {
    char c = file.read();
    
    if (c == '\n' || c == '\r') {
      if (bufIdx > 0) {
        lineBuffer[bufIdx] = '\0';
        
        CameraRecord record;
        if (parseCameraLine(lineBuffer, record)) {
          cameras.push_back(record);
        } else {
          parseErrors++;
        }
        
        lineCount++;
        bufIdx = 0;
        
        // Progress indicator every 1000 lines
        if (DEBUG_LOGS && lineCount % 1000 == 0) {
          Serial.printf("[Camera] Loaded %d cameras...\n", cameras.size());
        }
      }
    } else if (bufIdx < sizeof(lineBuffer) - 1) {
      lineBuffer[bufIdx++] = c;
    }
  }
  
  // Handle last line without newline
  if (bufIdx > 0) {
    lineBuffer[bufIdx] = '\0';
    CameraRecord record;
    if (parseCameraLine(lineBuffer, record)) {
      cameras.push_back(record);
    }
    lineCount++;
  }
  
  file.close();
  
  // Build spatial index for fast queries
  buildSpatialIndex();
  
  size_t addedCount = cameras.size() - startCount;
  uint32_t elapsed = millis() - startTime;
  Serial.printf("[Camera] Loaded %zu cameras from %s in %lums (%zu parse errors)\n", 
                addedCount, path, static_cast<unsigned long>(elapsed), parseErrors);
  
  // Log type breakdown
  if (DEBUG_LOGS) {
    Serial.printf("[Camera] Types: %d red light, %d speed, %d ALPR\n",
                  getRedLightCount(), getSpeedCameraCount(), getALPRCount());
  }
  
  return addedCount > 0;
}

// Binary format header structure (16 bytes, packed to match Python struct.pack('<4sIII'))
struct __attribute__((packed)) BinaryHeader {
  char magic[4];        // "VCAM" - 4 bytes
  uint32_t version;     // Format version (1) - 4 bytes
  uint32_t count;       // Number of camera records - 4 bytes
  uint32_t recordSize;  // Size of each record (24 bytes) - 4 bytes
};

// Binary record structure (24 bytes, packed)
struct __attribute__((packed)) BinaryRecord {
  float lat;            // 4 bytes
  float lon;            // 4 bytes
  float snapLat;        // 4 bytes - corridor snap point
  float snapLon;        // 4 bytes - corridor snap point
  int16_t bearing;      // 2 bytes - road bearing * 10
  uint8_t width;        // 1 byte  - corridor width in meters
  uint8_t tolerance;    // 1 byte  - bearing tolerance degrees
  uint8_t type;         // 1 byte  - camera type
  uint8_t speedLimit;   // 1 byte  - speed limit
  uint8_t flags;        // 1 byte  - packed flags (isMetric, etc.)
  uint8_t reserved;     // 1 byte  - padding for alignment
};

bool CameraManager::loadBinaryDatabase(const char* path, bool append) {
  if (!fs) return false;
  
  File file = fs->open(path, "r");
  if (!file) {
    Serial.printf("[Camera] Failed to open binary %s\n", path);
    return false;
  }
  
  // Clear existing data only if not appending
  if (!append) {
    clear();
  }
  
  Serial.printf("[Camera] Loading binary database from %s...\n", path);
  uint32_t startTime = millis();
  size_t startCount = cameras.size();
  
  // Read and validate header
  BinaryHeader header;
  if (file.read((uint8_t*)&header, sizeof(header)) != sizeof(header)) {
    Serial.printf("[Camera] Failed to read binary header\n");
    file.close();
    return false;
  }
  
  // Validate magic
  if (memcmp(header.magic, "VCAM", 4) != 0) {
    Serial.printf("[Camera] Invalid binary magic\n");
    file.close();
    return false;
  }
  
  // Check version
  if (header.version != 1) {
    Serial.printf("[Camera] Unsupported binary version: %lu\n",
                  static_cast<unsigned long>(header.version));
    file.close();
    return false;
  }
  
  // Validate record size
  if (header.recordSize != sizeof(BinaryRecord)) {
    Serial.printf("[Camera] Record size mismatch: expected %zu, got %lu\n", 
                  sizeof(BinaryRecord), static_cast<unsigned long>(header.recordSize));
    file.close();
    return false;
  }
  
  Serial.printf("[Camera] Binary file: %lu records, %lu bytes each\n", 
                static_cast<unsigned long>(header.count),
                static_cast<unsigned long>(header.recordSize));
  
  // Reserve space for efficiency
  cameras.reserve(cameras.size() + header.count);
  
  // Read records in batches for better performance
  const size_t BATCH_SIZE = 64;
  BinaryRecord batch[BATCH_SIZE];
  size_t remaining = header.count;
  size_t loaded = 0;
  
  while (remaining > 0) {
    size_t toRead = min(remaining, BATCH_SIZE);
    size_t bytesRead = file.read((uint8_t*)batch, toRead * sizeof(BinaryRecord));
    
    if (bytesRead != toRead * sizeof(BinaryRecord)) {
      Serial.printf("[Camera] Unexpected end of binary file\n");
      break;
    }
    
    for (size_t i = 0; i < toRead; i++) {
      CameraRecord record;
      record.latitude = batch[i].lat;
      record.longitude = batch[i].lon;
      record.snapLat = batch[i].snapLat;
      record.snapLon = batch[i].snapLon;
      record.roadBearing = batch[i].bearing / 10.0f;
      record.corridorWidthM = batch[i].width;
      record.bearingTolerance = batch[i].tolerance;
      record.type = batch[i].type;
      record.speedLimit = batch[i].speedLimit;
      record.isMetric = (batch[i].flags & 0x01) != 0;
      
      cameras.push_back(record);
      loaded++;
    }
    
    remaining -= toRead;
    
    // Progress indicator every 10000 records
    if (DEBUG_LOGS && loaded % 10000 == 0) {
      Serial.printf("[Camera] Loaded %d cameras...\n", loaded);
    }
  }
  
  file.close();
  
  // Build spatial index for fast queries
  buildSpatialIndex();
  
  size_t addedCount = cameras.size() - startCount;
  uint32_t elapsed = millis() - startTime;
  Serial.printf("[Camera] Loaded %zu cameras from %s in %lums (binary)\n", 
                addedCount, path, static_cast<unsigned long>(elapsed));
  
  return addedCount > 0;
}

bool CameraManager::parseCameraLine(const char* line, CameraRecord& record) {
  // Skip empty lines
  if (!line || line[0] == '\0') return false;
  
  // Parse JSON
  JsonDocument doc;
  DeserializationError error = deserializeJson(doc, line);
  
  if (error) {
    // Not JSON - might be metadata line or CSV
    return false;
  }
  
  // Check for metadata line (has _meta field) - use is<T>() for ArduinoJson 7.x
  if (doc["_meta"].is<JsonObject>()) {
    JsonObject meta = doc["_meta"];
    if (meta["name"].is<const char*>()) {
      strncpy(databaseName, meta["name"] | "", sizeof(databaseName) - 1);
    }
    if (meta["date"].is<const char*>()) {
      strncpy(databaseDate, meta["date"] | "", sizeof(databaseDate) - 1);
    }
    Serial.printf("[Camera] Database: %s (%s)\n", databaseName, databaseDate);
    return false;  // Not a camera record
  }
  
  // Must have lat/lon - use is<T>() for ArduinoJson 7.x
  if (!doc["lat"].is<float>() || !doc["lon"].is<float>()) {
    return false;
  }
  
  record.latitude = doc["lat"].as<float>();
  record.longitude = doc["lon"].as<float>();
  
  // Validate coordinates
  if (record.latitude < -90.0f || record.latitude > 90.0f ||
      record.longitude < -180.0f || record.longitude > 180.0f) {
    return false;
  }
  
  // Camera type from flg field
  // Note: flg values 1-3 are standard ExCam types, but ALPR uses flg=8192
  // We map 8192 to our internal ALPR type (4) since uint8_t can't hold 8192
  int flg = doc["flg"] | 2;  // Default to speed camera
  if (flg == 8192) {
    record.type = static_cast<uint8_t>(CameraType::ALPR);
  } else {
    record.type = static_cast<uint8_t>(flg);
  }
  
  // Speed limit (0 if not specified)
  record.speedLimit = doc["spd"] | 0;
  
  // Unit (default to mph for US)
  const char* unt = doc["unt"] | "mph";
  record.isMetric = (strcmp(unt, "kmh") == 0);
  
  // Directions array - use is<T>() for ArduinoJson 7.x
  record.directionCount = 0;
  if (doc["dir"].is<JsonArray>()) {
    JsonArray dirs = doc["dir"].as<JsonArray>();
    for (JsonVariant d : dirs) {
      if (record.directionCount < 2) {
        record.directions[record.directionCount++] = d.as<uint16_t>();
      }
    }
  }
  
  // Corridor data for road-aware filtering (optional enrichment fields)
  // Supports two formats:
  // 1. Online (download_cameras.py): rbr, cwm, btol, slat, slon
  // 2. Offline (PostGIS pipeline): p1, p2, brg, w
  
  // Check for PostGIS format first (p1/p2 arrays)
  if (doc["p1"].is<JsonArray>() && doc["p2"].is<JsonArray>()) {
    JsonArray p1 = doc["p1"].as<JsonArray>();
    JsonArray p2 = doc["p2"].as<JsonArray>();
    
    if (p1.size() >= 2 && p2.size() >= 2) {
      // p1 and p2 are corridor endpoints [lat, lon]
      float p1_lat = p1[0].as<float>();
      float p1_lon = p1[1].as<float>();
      float p2_lat = p2[0].as<float>();
      float p2_lon = p2[1].as<float>();
      
      // Use midpoint as snap point
      record.snapLat = (p1_lat + p2_lat) / 2.0f;
      record.snapLon = (p1_lon + p2_lon) / 2.0f;
      
      // Bearing from brg field
      record.roadBearing = doc["brg"] | -1;
      
      // Corridor width from w field (this is half-width in PostGIS format)
      record.corridorWidthM = doc["w"] | 35;
      
      // Default bearing tolerance
      record.bearingTolerance = 30;
    }
  } 
  // Fall back to online format (rbr/slat/slon)
  else {
    // roadBearing: -1 = not set, 0-359 = bearing in degrees
    record.roadBearing = doc["rbr"] | -1;
    // corridorWidthM: default 35m (typical 2-lane road width + margin)
    record.corridorWidthM = doc["cwm"] | 35;
    // bearingTolerance: default 30 degrees for heading match
    record.bearingTolerance = doc["btol"] | 30;
    // Snapped coordinates (road-centerline position)
    record.snapLat = doc["slat"] | record.latitude;
    record.snapLon = doc["slon"] | record.longitude;
  }
  
  return true;
}

void CameraManager::clear() {
  cameras.clear();
  regionalCache.clear();
  spatialIndex.clear();
  indexBuilt = false;
  databaseName[0] = '\0';
  databaseDate[0] = '\0';
  cacheCenterLat = 0.0f;
  cacheCenterLon = 0.0f;
  cacheRadiusMi = 0.0f;
  cacheBuiltMs = 0;
}

// Helper to get the active camera list (regional cache if available, else full DB)
// Thread-safety: returns regional cache if available (safe - only modified from main thread)
// If background loading and no cache, returns empty vector to avoid iterator invalidation
const CameraVector& CameraManager::getQueryCameras() const {
  if (!regionalCache.empty()) {
    return regionalCache;
  }
  // During background loading, cameras vector may be modified (push_back can reallocate)
  // Return empty vector to prevent iterator invalidation crash
  if (backgroundLoading) {
    static const CameraVector emptyVector;
    return emptyVector;
  }
  return cameras;
}

const CameraVector* CameraManager::getQueryCamerasSnapshot(
  CameraVector& snapshot
) const {
  if (!regionalCache.empty()) {
    return &regionalCache;
  }
  if (!backgroundLoading) {
    return &cameras;
  }
  if (cameraMutex && xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(10)) == pdTRUE) {
    snapshot = cameras;
    xSemaphoreGive(cameraMutex);
    return &snapshot;
  }
  return &cameras;
}

// Build regional cache containing only cameras within radius of GPS position
// Thread-safe: uses mutex when accessing full camera database
bool CameraManager::buildRegionalCache(float lat, float lon, float radiusMiles) {
  // Take mutex to safely read cameras vector (may be modified by background task)
  if (!cameraMutex || xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(100)) != pdTRUE) {
    Serial.println("[Camera] Cannot build cache - mutex unavailable");
    return false;
  }
  
  if (cameras.empty()) {
    xSemaphoreGive(cameraMutex);
    Serial.println("[Camera] Cannot build cache - no database loaded");
    return false;
  }
  
  uint32_t startTime = millis();
  regionalCache.clear();
  
  // Convert miles to meters for haversine
  float radiusM = radiusMiles * 1609.34f;
  
  // Pre-calculate bounding box for quick filtering
  float latDelta = radiusM / 111000.0f;
  float lonDelta = radiusM / (111000.0f * cos(lat * PI / 180.0f));
  
  // Copy cameras within radius
  for (const auto& cam : cameras) {
    // Quick bounding box check
    if (fabs(cam.latitude - lat) > latDelta) continue;
    if (fabs(cam.longitude - lon) > lonDelta) continue;
    
    // Precise distance check
    float dist = haversineDistance(lat, lon, cam.latitude, cam.longitude);
    if (dist <= radiusM) {
      regionalCache.push_back(cam);
    }
  }
  
  // Store cache metadata
  cacheCenterLat = lat;
  cacheCenterLon = lon;
  cacheRadiusMi = radiusMiles;
  cacheBuiltMs = millis();
  
  // Release mutex now that we're done reading cameras
  xSemaphoreGive(cameraMutex);
  
  uint32_t elapsed = millis() - startTime;
  Serial.printf("[Camera] Regional cache: %zu of %zu cameras within %.0f mi (took %lums)\n",
                regionalCache.size(), cameras.size(), radiusMiles,
                static_cast<unsigned long>(elapsed));
  
  return !regionalCache.empty();
}

// Check if cache needs refresh based on distance from cache center
bool CameraManager::needsCacheRefresh(float lat, float lon, float distanceThresholdMiles) const {
  // No cache exists - needs refresh
  if (regionalCache.empty() || cacheRadiusMi == 0.0f) {
    return true;
  }
  
  // Check distance from cache center
  float distM = haversineDistance(lat, lon, cacheCenterLat, cacheCenterLon);
  float distMiles = distM / 1609.34f;
  
  // If moved more than threshold, refresh needed
  if (distMiles > distanceThresholdMiles) {
    if (DEBUG_LOGS) {
      Serial.printf("[Camera] Cache refresh needed: moved %.1f mi from cache center\n", distMiles);
    }
    return true;
  }
  
  return false;
}

// Save regional cache to LittleFS for fast boot
bool CameraManager::saveRegionalCache(fs::FS* filesystem, const char* path) {
  if (regionalCache.empty()) {
    Serial.println("[Camera] No regional cache to save");
    return false;
  }
  
  if (!filesystem) {
    Serial.println("[Camera] No filesystem for cache save");
    return false;
  }
  
  uint32_t startTime = millis();
  
  File file = filesystem->open(path, "w");
  if (!file) {
    Serial.printf("[Camera] Failed to open %s for writing\n", path);
    return false;
  }
  
  // Write metadata line first
  char metaLine[128];
  snprintf(metaLine, sizeof(metaLine), 
           "{\"_cache\":{\"lat\":%.6f,\"lon\":%.6f,\"radius\":%.1f,\"count\":%d}}\n",
           cacheCenterLat, cacheCenterLon, cacheRadiusMi, regionalCache.size());
  file.print(metaLine);
  
  // Write camera records as NDJSON
  char line[256];  // Expanded for corridor fields
  for (const auto& cam : regionalCache) {
    int len = snprintf(line, sizeof(line), 
                       "{\"lat\":%.6f,\"lon\":%.6f,\"flg\":%d",
                       cam.latitude, cam.longitude, cam.type);
    
    if (cam.speedLimit > 0) {
      len += snprintf(line + len, sizeof(line) - len, ",\"spd\":%d", cam.speedLimit);
    }
    
    if (cam.directionCount > 0) {
      len += snprintf(line + len, sizeof(line) - len, ",\"dir\":[%d", cam.directions[0]);
      if (cam.directionCount > 1) {
        len += snprintf(line + len, sizeof(line) - len, ",%d", cam.directions[1]);
      }
      len += snprintf(line + len, sizeof(line) - len, "]");
    }
    
    // Write corridor fields only if we have corridor data
    if (cam.hasCorridorData()) {
      len += snprintf(line + len, sizeof(line) - len, 
                      ",\"rbr\":%d,\"cwm\":%d,\"btol\":%d,\"slat\":%.6f,\"slon\":%.6f",
                      cam.roadBearing, cam.corridorWidthM, cam.bearingTolerance,
                      cam.snapLat, cam.snapLon);
    }
    
    len += snprintf(line + len, sizeof(line) - len, "}\n");
    file.print(line);
  }
  
  file.close();
  
  uint32_t elapsed = millis() - startTime;
  Serial.printf("[Camera] Saved %zu cameras to cache in %lums\n",
                regionalCache.size(), static_cast<unsigned long>(elapsed));
  
  return true;
}

// Load regional cache from LittleFS (for fast boot before full DB load)
bool CameraManager::loadRegionalCache(fs::FS* filesystem, const char* path) {
  if (!filesystem) {
    return false;
  }
  
  if (!filesystem->exists(path)) {
    if (DEBUG_LOGS) {
      Serial.printf("[Camera] No cache file at %s\n", path);
    }
    return false;
  }
  
  File file = filesystem->open(path, "r");
  if (!file) {
    return false;
  }
  
  uint32_t startTime = millis();
  regionalCache.clear();
  
  char lineBuffer[256];
  size_t bufIdx = 0;
  bool metaFound = false;
  
  while (file.available()) {
    char c = file.read();
    
    if (c == '\n' || c == '\r') {
      if (bufIdx > 0) {
        lineBuffer[bufIdx] = '\0';
        
        // Parse line
        JsonDocument doc;
        DeserializationError error = deserializeJson(doc, lineBuffer);
        
        if (!error) {
          // Check for metadata line
          if (doc["_cache"].is<JsonObject>()) {
            JsonObject meta = doc["_cache"];
            cacheCenterLat = meta["lat"] | 0.0f;
            cacheCenterLon = meta["lon"] | 0.0f;
            cacheRadiusMi = meta["radius"] | 0.0f;
            metaFound = true;
          } else {
            // Regular camera record
            CameraRecord record;
            if (parseCameraLine(lineBuffer, record)) {
              regionalCache.push_back(record);
            }
          }
        }
        
        bufIdx = 0;
      }
    } else if (bufIdx < sizeof(lineBuffer) - 1) {
      lineBuffer[bufIdx++] = c;
    }
  }
  
  file.close();
  
  if (regionalCache.empty() || !metaFound) {
    Serial.println("[Camera] Cache load failed - invalid or empty cache");
    regionalCache.clear();
    return false;
  }
  
  cacheBuiltMs = millis();
  uint32_t elapsed = millis() - startTime;
  Serial.printf("[Camera] Loaded %zu cached cameras in %lums (center: %.4f,%.4f)\n",
                regionalCache.size(), static_cast<unsigned long>(elapsed),
                cacheCenterLat, cacheCenterLon);
  
  return true;
}

void CameraManager::buildSpatialIndex() {
  // For now, skip complex spatial indexing
  // The brute-force search is fast enough for <20k cameras
  // A spatial index would be needed for >100k cameras
  indexBuilt = true;
  
  if (DEBUG_LOGS) {
    Serial.printf("[Camera] Spatial index ready for %d cameras\n", cameras.size());
  }
}

int CameraManager::getGridIndex(float lat, float lon) const {
  int latCell = static_cast<int>((lat + 90.0f) / GRID_SIZE_DEG);
  int lonCell = static_cast<int>((lon + 180.0f) / GRID_SIZE_DEG);
  
  latCell = constrain(latCell, 0, GRID_LAT_CELLS - 1);
  lonCell = constrain(lonCell, 0, GRID_LON_CELLS - 1);
  
  return latCell * GRID_LON_CELLS + lonCell;
}

float CameraManager::haversineDistance(float lat1, float lon1, float lat2, float lon2) {
  const float R = 6371000.0f;  // Earth radius in meters
  
  float dLat = (lat2 - lat1) * PI / 180.0f;
  float dLon = (lon2 - lon1) * PI / 180.0f;
  
  float a = sin(dLat/2) * sin(dLat/2) +
            cos(lat1 * PI / 180.0f) * cos(lat2 * PI / 180.0f) *
            sin(dLon/2) * sin(dLon/2);
  
  float c = 2 * atan2(sqrt(a), sqrt(1-a));
  
  return R * c;
}

float CameraManager::calculateBearing(float lat1, float lon1, float lat2, float lon2) {
  float dLon = (lon2 - lon1) * PI / 180.0f;
  float lat1Rad = lat1 * PI / 180.0f;
  float lat2Rad = lat2 * PI / 180.0f;
  
  float x = sin(dLon) * cos(lat2Rad);
  float y = cos(lat1Rad) * sin(lat2Rad) - sin(lat1Rad) * cos(lat2Rad) * cos(dLon);
  
  float bearing = atan2(x, y) * 180.0f / PI;
  
  // Normalize to 0-360
  if (bearing < 0) bearing += 360.0f;
  
  return bearing;
}

bool CameraManager::isHeadingTowards(float heading, float bearing, float tolerance) {
  float diff = fabs(heading - bearing);
  if (diff > 180.0f) diff = 360.0f - diff;
  return diff <= tolerance;
}

float CameraManager::angleDiff(float angle1, float angle2) {
  float diff = fabs(angle1 - angle2);
  if (diff > 180.0f) diff = 360.0f - diff;
  return diff;
}

float CameraManager::crossTrackDistance(
  float lat, float lon,
  float roadLat, float roadLon,
  int16_t roadBearing
) {
  // Cross-track distance: perpendicular distance from point to infinite line
  // Line defined by roadLat/roadLon with bearing roadBearing
  // 
  // Formula: d_xt = asin(sin(d_13/R) * sin(θ_13 - θ_12)) * R
  // Where:
  //   d_13 = distance from road point to vehicle
  //   θ_13 = bearing from road point to vehicle
  //   θ_12 = road bearing
  
  float dist = haversineDistance(roadLat, roadLon, lat, lon);
  if (dist < 1.0f) return 0.0f;  // On the point
  
  float bearingToVehicle = calculateBearing(roadLat, roadLon, lat, lon);
  float bearingDiff = (bearingToVehicle - static_cast<float>(roadBearing)) * PI / 180.0f;
  
  // Cross-track distance (signed, but we want absolute)
  float xtd = fabs(sin(bearingDiff) * dist);
  
  return xtd;
}

bool CameraManager::isOnCameraRoad(
  float lat, float lon, float heading,
  const CameraRecord& cam
) const {
  // If no corridor data, fall back to simple distance check
  if (!cam.hasCorridorData()) {
    return true;  // Assume on-road if no data
  }
  
  // Check cross-track distance (perpendicular distance to road centerline)
  float xtd = crossTrackDistance(lat, lon, cam.snapLat, cam.snapLon, cam.roadBearing);
  if (xtd > static_cast<float>(cam.corridorWidthM)) {
    return false;  // Too far from road centerline
  }
  
  // Check heading alignment with road bearing
  // Road can be traveled in either direction, so check both
  float headingDiff = angleDiff(heading, static_cast<float>(cam.roadBearing));
  float reverseHeadingDiff = angleDiff(heading, fmod(static_cast<float>(cam.roadBearing) + 180.0f, 360.0f));
  float minHeadingDiff = fmin(headingDiff, reverseHeadingDiff);
  
  if (minHeadingDiff > static_cast<float>(cam.bearingTolerance)) {
    return false;  // Heading doesn't match road direction
  }
  
  return true;
}

bool CameraManager::hasNearbyCamera(float lat, float lon, float radius_m) const {
  CameraVector snapshot;
  const auto* queryList = getQueryCamerasSnapshot(snapshot);
  if (!queryList || queryList->empty()) return false;
  
  // Quick bounding box check first
  // At 45° latitude, 1° ≈ 111km lat, 78km lon
  float latDelta = radius_m / 111000.0f;
  float lonDelta = radius_m / (111000.0f * cos(lat * PI / 180.0f));
  
  for (const auto& cam : *queryList) {
    // Quick box check
    if (fabs(cam.latitude - lat) > latDelta) continue;
    if (fabs(cam.longitude - lon) > lonDelta) continue;
    
    // Type filter
    if (!isTypeEnabled(cam.getCameraType())) continue;
    
    // Precise distance check
    float dist = haversineDistance(lat, lon, cam.latitude, cam.longitude);
    if (dist <= radius_m) {
      return true;
    }
  }
  
  return false;
}

bool CameraManager::getClosestCamera(
  float lat, float lon,
  float heading_deg,
  float radius_m,
  NearbyCameraResult& result
) const {
  CameraVector snapshot;
  const auto* queryList = getQueryCamerasSnapshot(snapshot);
  if (!queryList || queryList->empty()) return false;
  
  float closestDist = radius_m + 1.0f;
  bool found = false;
  
  // Quick bounding box
  float latDelta = radius_m / 111000.0f;
  float lonDelta = radius_m / (111000.0f * cos(lat * PI / 180.0f));
  
  for (const auto& cam : *queryList) {
    // Quick box check
    if (fabs(cam.latitude - lat) > latDelta) continue;
    if (fabs(cam.longitude - lon) > lonDelta) continue;
    
    // Type filter
    if (!isTypeEnabled(cam.getCameraType())) continue;
    
    // Precise distance
    float dist = haversineDistance(lat, lon, cam.latitude, cam.longitude);
    if (dist > radius_m) continue;
    
    // Corridor check - skip cameras if we're not on their road
    if (!isOnCameraRoad(lat, lon, heading_deg, cam)) continue;
    
    // Prioritize cameras we're heading towards
    float bearing = calculateBearing(lat, lon, cam.latitude, cam.longitude);
    bool approaching = isHeadingTowards(heading_deg, bearing, 60.0f);
    
    // Prefer closer cameras and those we're approaching
    float effectiveDist = approaching ? dist * 0.5f : dist;
    
    if (effectiveDist < closestDist) {
      closestDist = effectiveDist;
      result.camera = cam;
      result.distance_m = dist;
      result.bearing_deg = bearing;
      result.isApproaching = approaching;
      found = true;
    }
  }
  
  return found;
}

void CameraManager::findNearby(
  float lat, float lon,
  float heading_deg,
  float radius_m,
  size_t maxResults,
  std::vector<NearbyCameraResult>& out
) const {
  out.clear();  // Clear but keep capacity for reuse
  
  CameraVector snapshot;
  const auto* queryList = getQueryCamerasSnapshot(snapshot);
  if (!queryList || queryList->empty()) return;

  // Quick bounding box
  float latDelta = radius_m / 111000.0f;
  float lonDelta = radius_m / (111000.0f * cos(lat * PI / 180.0f));
  
  for (const auto& cam : *queryList) {
    // Quick box check
    if (fabs(cam.latitude - lat) > latDelta) continue;
    if (fabs(cam.longitude - lon) > lonDelta) continue;
    
    // Type filter
    if (!isTypeEnabled(cam.getCameraType())) continue;
    
    // Precise distance
    float dist = haversineDistance(lat, lon, cam.latitude, cam.longitude);
    if (dist > radius_m) continue;
    
    // Corridor check - skip cameras if we're not on their road
    if (!isOnCameraRoad(lat, lon, heading_deg, cam)) continue;
    
    NearbyCameraResult r;
    r.camera = cam;
    r.distance_m = dist;
    r.bearing_deg = calculateBearing(lat, lon, cam.latitude, cam.longitude);
    r.isApproaching = isHeadingTowards(heading_deg, r.bearing_deg, 60.0f);
    
    out.push_back(r);
  }
  
  // Sort by distance (approaching cameras get priority)
  std::sort(out.begin(), out.end(), [](const NearbyCameraResult& a, const NearbyCameraResult& b) {
    // Approaching cameras are prioritized
    if (a.isApproaching != b.isApproaching) {
      return a.isApproaching;
    }
    return a.distance_m < b.distance_m;
  });
  
  // Limit results
  if (out.size() > maxResults) {
    out.resize(maxResults);
  }
}

void CameraManager::setEnabledTypes(bool redLight, bool speed, bool alpr) {
  enableRedLight = redLight;
  enableSpeed = speed;
  enableALPR = alpr;
}

bool CameraManager::isTypeEnabled(CameraType type) const {
  switch (type) {
    case CameraType::RedLightCamera:
    case CameraType::RedLightAndSpeed:
      return enableRedLight;
    case CameraType::SpeedCamera:
      return enableSpeed;
    case CameraType::ALPR:
      return enableALPR;
    default:
      return true;
  }
}

size_t CameraManager::getRedLightCount() const {
  CameraVector snapshot;
  const auto* queryList = getQueryCamerasSnapshot(snapshot);
  size_t count = 0;
  if (!queryList) return count;
  for (const auto& cam : *queryList) {
    if (cam.type == static_cast<uint8_t>(CameraType::RedLightCamera) ||
        cam.type == static_cast<uint8_t>(CameraType::RedLightAndSpeed)) {
      count++;
    }
  }
  return count;
}

size_t CameraManager::getSpeedCameraCount() const {
  CameraVector snapshot;
  const auto* queryList = getQueryCamerasSnapshot(snapshot);
  size_t count = 0;
  if (!queryList) return count;
  for (const auto& cam : *queryList) {
    if (cam.type == static_cast<uint8_t>(CameraType::SpeedCamera) ||
        cam.type == static_cast<uint8_t>(CameraType::RedLightAndSpeed)) {
      count++;
    }
  }
  return count;
}

size_t CameraManager::getALPRCount() const {
  CameraVector snapshot;
  const auto* queryList = getQueryCamerasSnapshot(snapshot);
  size_t count = 0;
  if (!queryList) return count;
  for (const auto& cam : *queryList) {
    if (cam.type == static_cast<uint8_t>(CameraType::ALPR)) {
      count++;
    }
  }
  return count;
}

// =========================================================================
// Background Loading Implementation
// =========================================================================

// Thread-safe camera count access
size_t CameraManager::getLoadedCount() const {
  if (cameraMutex && xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(10)) == pdTRUE) {
    size_t count = cameras.size();
    xSemaphoreGive(cameraMutex);
    return count;
  }
  return cameras.size();  // Fall back to unsynchronized if mutex fails
}

// Static task entry point - calls instance method
void CameraManager::loadTaskEntry(void* param) {
  CameraManager* self = static_cast<CameraManager*>(param);
  
  Serial.println("[Camera] Background load task started");
  
  // Perform the incremental database load
  bool success = self->loadDatabaseIncremental();
  
  // Mark loading complete
  self->backgroundLoading = false;
  self->loadProgressPercent = success ? 100 : 0;
  
  Serial.printf("[Camera] Background load task complete: %s (%d cameras)\n",
                success ? "success" : "failed", self->cameras.size());
  
  // Delete the task (task deletes itself when done)
  self->loadTaskHandle = nullptr;
  vTaskDelete(NULL);
}

// Start background loading - returns immediately
bool CameraManager::startBackgroundLoad() {
  if (!fs) {
    Serial.println("[Camera] Cannot start background load - no filesystem");
    return false;
  }
  
  if (backgroundLoading) {
    Serial.println("[Camera] Background load already in progress");
    return false;
  }
  
  // Mark loading as in progress
  backgroundLoading = true;
  loadProgressPercent = 0;
  loadTaskShouldExit = false;
  
  // Create background task with low priority (1)
  // Lower than BLE (5) and display (2) to avoid interfering with UI
  // Stack size increased to 8192 for binary batch buffer (64 * 24 = 1536 bytes)
  BaseType_t result = xTaskCreate(
    loadTaskEntry,          // Task function
    "CamLoad",              // Task name
    8192,                   // Stack size (bytes) - increased for binary loading
    this,                   // Parameter (this pointer)
    1,                      // Priority (low)
    &loadTaskHandle         // Task handle
  );
  
  if (result != pdPASS) {
    Serial.println("[Camera] Failed to create background load task");
    backgroundLoading = false;
    return false;
  }
  
  Serial.println("[Camera] Background load task created");
  return true;
}

// Stop background loading (if in progress)
void CameraManager::stopBackgroundLoad() {
  if (!backgroundLoading || !loadTaskHandle) {
    return;
  }
  
  Serial.println("[Camera] Stopping background load...");
  loadTaskShouldExit = true;
  
  // Wait for task to exit (up to 2 seconds)
  for (int i = 0; i < 20 && loadTaskHandle; i++) {
    vTaskDelay(pdMS_TO_TICKS(100));
  }
  
  // Force delete if still running
  if (loadTaskHandle) {
    vTaskDelete(loadTaskHandle);
    loadTaskHandle = nullptr;
    Serial.println("[Camera] Background load task forcefully terminated");
  }
  
  backgroundLoading = false;
}

// Incremental database load with yielding - called from background task
bool CameraManager::loadDatabaseIncremental() {
  // List of database files to load (in order)
  // Check for binary files first, then fall back to JSON
  struct DatabaseFile {
    const char* binPath;
    const char* jsonPath;
    bool useBinary;
    bool exists;
    size_t approxRecords;  // Estimate for progress calculation
  };
  
  DatabaseFile files[] = {
    {"/alpr.bin", "/alpr.json", false, false, 70000},
    {"/redlight_cam.bin", "/redlight_cam.json", false, false, 200},
    {"/speed_cam.bin", "/speed_cam.json", false, false, 1200}
  };
  const int numFiles = sizeof(files) / sizeof(files[0]);
  
  // Check which files exist (prefer binary)
  size_t totalRecords = 0;
  int existingFiles = 0;
  for (int i = 0; i < numFiles; i++) {
    if (fs->exists(files[i].binPath)) {
      files[i].exists = true;
      files[i].useBinary = true;
      totalRecords += files[i].approxRecords;
      existingFiles++;
    } else if (fs->exists(files[i].jsonPath)) {
      files[i].exists = true;
      files[i].useBinary = false;
      totalRecords += files[i].approxRecords;
      existingFiles++;
    }
  }
  
  if (existingFiles == 0) {
    Serial.println("[Camera] No database files found for background load");
    return false;
  }
  
  Serial.printf("[Camera] Background loading %d files (~%d records)...\n", 
                existingFiles, totalRecords);
  
  uint32_t overallStart = millis();
  size_t recordsLoaded = 0;
  bool firstFile = true;
  
  for (int fileIdx = 0; fileIdx < numFiles; fileIdx++) {
    if (loadTaskShouldExit) {
      Serial.println("[Camera] Background load cancelled");
      return false;
    }
    
    if (!files[fileIdx].exists) continue;
    
    const char* path = files[fileIdx].useBinary ? 
                       files[fileIdx].binPath : files[fileIdx].jsonPath;
    
    // Clear cameras only for first file
    if (firstFile) {
      if (cameraMutex && xSemaphoreTake(cameraMutex, portMAX_DELAY) == pdTRUE) {
        cameras.clear();
        cameras.reserve(totalRecords + 1000);
        xSemaphoreGive(cameraMutex);
      }
      firstFile = false;
    }
    
    uint32_t fileStart = millis();
    size_t fileRecords = 0;
    
    if (files[fileIdx].useBinary) {
      // Fast binary load
      fileRecords = loadBinaryDatabaseIncremental(path);
    } else {
      // Slow JSON load with yielding
      fileRecords = loadJsonDatabaseIncremental(path);
    }
    
    recordsLoaded += fileRecords;
    
    // Update progress
    loadProgressPercent = (totalRecords > 0) ? 
                          (recordsLoaded * 100 / totalRecords) : 0;
    
    uint32_t fileElapsed = millis() - fileStart;
    Serial.printf("[Camera] Loaded %zu from %s in %lums (bg%s)\n", 
                  fileRecords, path, static_cast<unsigned long>(fileElapsed),
                  files[fileIdx].useBinary ? ",bin" : "");
  }
  
  // Build spatial index after all files loaded
  buildSpatialIndex();
  
  loadProgressPercent = 100;
  
  uint32_t totalElapsed = millis() - overallStart;
  Serial.printf("[Camera] Background load complete: %zu cameras in %lums\n",
                cameras.size(), static_cast<unsigned long>(totalElapsed));
  
  return !cameras.empty();
}

// Load binary file incrementally (with task yielding)
size_t CameraManager::loadBinaryDatabaseIncremental(const char* path) {
  File file = fs->open(path, "r");
  if (!file) {
    Serial.printf("[Camera] FAIL open %s\n", path);
    return 0;
  }
  
  // Read header manually to avoid alignment issues on ESP32
  // Binary format: VCAM (4) + version (4, uint32 LE) + count (4, LE) + recordSize (4, LE) = 16 bytes
  uint8_t headerBuf[16];
  size_t bytesRead = file.read(headerBuf, 16);
  
  if (bytesRead != 16) {
    Serial.printf("[Camera] FAIL header %s\n", path);
    file.close();
    return 0;
  }
  
  // Parse header fields manually (little-endian, all 4-byte fields after magic)
  char magic[5] = {(char)headerBuf[0], (char)headerBuf[1], (char)headerBuf[2], (char)headerBuf[3], 0};
  uint32_t version = headerBuf[4] | (headerBuf[5] << 8) | (headerBuf[6] << 16) | (headerBuf[7] << 24);
  uint32_t count = headerBuf[8] | (headerBuf[9] << 8) | (headerBuf[10] << 16) | (headerBuf[11] << 24);
  uint32_t recordSize = headerBuf[12] | (headerBuf[13] << 8) | (headerBuf[14] << 16) | (headerBuf[15] << 24);
  
  if (memcmp(magic, "VCAM", 4) != 0) {
    Serial.printf("[Camera] Bad magic %s\n", path);
    file.close();
    return 0;
  }
  
  if (version != 1) {
    Serial.printf("[Camera] Bad version %s\n", path);
    file.close();
    return 0;
  }
  
  // Handle legacy files that wrote recordSize=0
  if (recordSize == 0) {
    recordSize = sizeof(BinaryRecord);  // Default to 24
  }
  
  if (recordSize != sizeof(BinaryRecord)) {
    Serial.printf("[Camera] Bad recSize %s\n", path);
    file.close();
    return 0;
  }
  
  // Read records in batches (128 records × 24 bytes = 3KB stack, safe for ESP32-S3)
  const size_t BATCH_SIZE = 128;
  BinaryRecord batch[BATCH_SIZE];
  size_t remaining = count;
  size_t loaded = 0;
  
  while (remaining > 0 && !loadTaskShouldExit) {
    size_t toRead = (remaining > BATCH_SIZE) ? BATCH_SIZE : remaining;
    size_t bytesRead = file.read((uint8_t*)batch, toRead * sizeof(BinaryRecord));
    
    if (bytesRead != toRead * sizeof(BinaryRecord)) {
      Serial.println("[Camera] Unexpected end of binary file");
      break;
    }
    
    // Add to camera vector (thread-safe)
    if (cameraMutex && xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(50)) == pdTRUE) {
      for (size_t i = 0; i < toRead; i++) {
        CameraRecord record;
        record.latitude = batch[i].lat;
        record.longitude = batch[i].lon;
        record.snapLat = batch[i].snapLat;
        record.snapLon = batch[i].snapLon;
        record.roadBearing = batch[i].bearing / 10.0f;
        record.corridorWidthM = batch[i].width;
        record.bearingTolerance = batch[i].tolerance;
        record.type = batch[i].type;
        record.speedLimit = batch[i].speedLimit;
        record.isMetric = (batch[i].flags & 0x01) != 0;
        cameras.push_back(record);
      }
      xSemaphoreGive(cameraMutex);
    }
    
    loaded += toRead;
    remaining -= toRead;
    
    // Yield every batch to allow other tasks to run
    vTaskDelay(pdMS_TO_TICKS(1));
  }
  
  file.close();
  return loaded;
}

// Load JSON file incrementally (with task yielding) - slow path
size_t CameraManager::loadJsonDatabaseIncremental(const char* path) {
  File file = fs->open(path, "r");
  if (!file) {
    Serial.printf("[Camera] Failed to open %s\n", path);
    return 0;
  }
  
  size_t fileRecords = 0;
  size_t linesProcessed = 0;
  char lineBuffer[256];
  size_t bufIdx = 0;
  
  while (file.available()) {
    // Check for cancellation and yield every 100 lines
    if ((linesProcessed % 100) == 0) {
      if (loadTaskShouldExit) {
        file.close();
        return fileRecords;
      }
      vTaskDelay(pdMS_TO_TICKS(1));
    }
    
    char c = file.read();
    
    if (c == '\n' || c == '\r') {
      if (bufIdx > 0) {
        lineBuffer[bufIdx] = '\0';
        
        CameraRecord record;
        if (parseCameraLine(lineBuffer, record)) {
          if (cameraMutex && xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(50)) == pdTRUE) {
            cameras.push_back(record);
            xSemaphoreGive(cameraMutex);
            fileRecords++;
          }
        }
        
        linesProcessed++;
        bufIdx = 0;
      }
    } else if (bufIdx < sizeof(lineBuffer) - 1) {
      lineBuffer[bufIdx++] = c;
    }
  }
  
  // Handle last line without newline
  if (bufIdx > 0) {
    lineBuffer[bufIdx] = '\0';
    CameraRecord record;
    if (parseCameraLine(lineBuffer, record)) {
      if (cameraMutex && xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(50)) == pdTRUE) {
        cameras.push_back(record);
        xSemaphoreGive(cameraMutex);
        fileRecords++;
      }
    }
  }
  
  file.close();
  return fileRecords;
}
// ============================================================================
// Incremental Cache Building - Non-blocking cache construction
// ============================================================================

bool CameraManager::startIncrementalCacheBuild(float lat, float lon, float radiusMiles) {
  // Don't start if already in progress
  if (incrementalBuild.inProgress) {
    Serial.println("[Camera] Incremental build already in progress");
    return false;
  }
  
  // Convert radius to meters and calculate lat/lon deltas for quick filtering
  float radiusM = radiusMiles * 1609.34f;
  float latDelta = radiusM / 111320.0f;  // ~111km per degree latitude
  float lonDelta = radiusM / (111320.0f * cosf(lat * DEG_TO_RAD));
  
  // Initialize incremental state
  incrementalBuild.inProgress = true;
  incrementalBuild.currentIndex = 0;
  incrementalBuild.targetLat = lat;
  incrementalBuild.targetLon = lon;
  incrementalBuild.radiusM = radiusM;
  incrementalBuild.latDelta = latDelta;
  incrementalBuild.lonDelta = lonDelta;
  incrementalBuild.pendingCache.clear();
  incrementalBuild.pendingCache.reserve(500);  // Reserve reasonable space
  incrementalBuild.startTimeMs = millis();
  incrementalBuild.radiusMi = radiusMiles;  // Store for finish
  
  Serial.printf("[Camera] Starting incremental cache build: %.6f, %.6f, %.0f mi\n",
                lat, lon, radiusMiles);
  
  return true;
}

bool CameraManager::continueIncrementalCacheBuild(size_t maxCamerasPerCall) {
  if (!incrementalBuild.inProgress) {
    return true;  // Nothing to do, consider it complete
  }
  
  // Brief mutex acquisition to read camera data
  if (!cameraMutex || xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(10)) != pdTRUE) {
    return false;  // Couldn't get mutex, try again later
  }
  
  size_t totalCameras = cameras.size();
  size_t processed = 0;
  
  while (incrementalBuild.currentIndex < totalCameras && processed < maxCamerasPerCall) {
    const CameraRecord& cam = cameras[incrementalBuild.currentIndex];
    
    // Quick bounding box check first (very fast)
    float latDiff = fabsf(cam.latitude - incrementalBuild.targetLat);
    float lonDiff = fabsf(cam.longitude - incrementalBuild.targetLon);
    
    if (latDiff <= incrementalBuild.latDelta && lonDiff <= incrementalBuild.lonDelta) {
      // Within bounding box, do precise distance check
      float dist = haversineDistance(cam.latitude, cam.longitude,
                                     incrementalBuild.targetLat, incrementalBuild.targetLon);
      if (dist <= incrementalBuild.radiusM) {
        incrementalBuild.pendingCache.push_back(cam);
      }
    }
    
    incrementalBuild.currentIndex++;
    processed++;
  }
  
  xSemaphoreGive(cameraMutex);
  
  // Check if complete
  if (incrementalBuild.currentIndex >= totalCameras) {
    return true;  // Build complete
  }
  
  return false;  // More work to do
}

bool CameraManager::finishIncrementalCacheBuild() {
  if (!incrementalBuild.inProgress) {
    return false;
  }
  
  // Brief mutex to swap the cache
  if (cameraMutex && xSemaphoreTake(cameraMutex, pdMS_TO_TICKS(50)) == pdTRUE) {
    // Move the pending cache to the active cache
    regionalCache = std::move(incrementalBuild.pendingCache);
    cacheCenterLat = incrementalBuild.targetLat;
    cacheCenterLon = incrementalBuild.targetLon;
    cacheRadiusMi = incrementalBuild.radiusMi;
    xSemaphoreGive(cameraMutex);
  }
  
  uint32_t elapsed = millis() - incrementalBuild.startTimeMs;
  Serial.printf("[Camera] Incremental cache complete: %zu cameras in %lu ms (non-blocking)\n",
                regionalCache.size(), static_cast<unsigned long>(elapsed));
  
  // Reset state
  incrementalBuild.inProgress = false;
  incrementalBuild.pendingCache.clear();
  incrementalBuild.pendingCache.shrink_to_fit();  // Release memory
  
  return true;
}
